name: CallRail 30-Day Data Fetch

on:
  schedule:
    # Run daily at 9 AM UTC (adjust as needed)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-callrail-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create service account file
      run: echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > service_account.json
    
    - name: Run CallRail fetch script
      env:
        CALLRAIL_API_KEY: ${{ secrets.CALLRAIL_API_KEY }}
        CALLRAIL_ACCOUNT_ID: ${{ secrets.CALLRAIL_ACCOUNT_ID }}
      run: python callrail_fetch.py
