name: Import Leads from Google Sheet

on:
  schedule:
    # Run every 2 minutes to check for new leads
    - cron: '*/2 * * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [new_lead_added]

jobs:
  import-leads:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Create service account file
      run: |
        echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > service_account.json
    
    - name: Import leads to Odoo Test Environment
      env:
        ODOO_URL: "https://qa-odoo.apps.optimacompanies.com/"
        ODOO_DB: "prod-restore-20250409"
        ODOO_LOGIN: ${{ secrets.ODOO_LOGIN }}
        ODOO_PASSWORD: ${{ secrets.ODOO_PASSWORD }}
      run: |
        python lead_import_from_sheet.py
