name: Odoo Monthly Meeting Scheduler

on:
  schedule:
  #  - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install
          playwright install-deps
          
      - name: Run scheduler script
        env:
          ODOO_USERNAME: ${{ secrets.ODOO_USERNAME }}
          ODOO_PASSWORD: ${{ secrets.ODOO_PASSWORD }}
        run: python odoo-scheduler.py
