name: Whiteboard Price Check

on:
  schedule:
    - cron: '0 14 * * *'  # Runs at 14:00 UTC daily (adjust time as needed)
  workflow_dispatch:  # Allows manual triggers

jobs:
  check-price:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright google-auth gspread
          playwright install
          playwright install-deps
          
      - name: Create credentials file
        run: |
          echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > credentials.json
          
      - name: Run price check
        run: python main.py
